[profile.default]
src = "../../contracts"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
solc = "0.8.24"
remappings = [
    "contracts/=../../contracts/"
]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
